package com.guardianai.model;

import jakarta.persistence.*; // Or javax.persistence.* for older Spring Boot versions
import java.time.LocalDateTime; // Or java.time.OffsetDateTime for timezone awareness
import java.util.UUID; // If you want UUIDs as per the solution

@Entity // Marks this class as a JPA entity, meaning it maps to a database table
@Table(name = "audit_logs") // Specifies the name of the database table
public class AuditLog {

    @Id // Marks this field as the primary key
    // @GeneratedValue(strategy = GenerationType.IDENTITY) // For auto-incrementing Long IDs (MariaDB, PostgreSQL)
    // If you want UUID as per the solution:
    // @GeneratedValue(strategy = GenerationType.UUID) // For Hibernate 6+ with UUID support
    // private UUID id; // Change type to UUID if using UUIDs
    // For now, sticking with Long as you provided it, but noting the UUID option
    private Long id;


    @Column(nullable = false) // Maps to a database column, original is NOT NULL
    private String original;

    @Column(nullable = false) // sanitized is NOT NULL
    private String sanitized;

    @Column(name = "pii") // Explicitly names the column "pii"
    private boolean piiDetected;

    @Column(name = "nsfw") // Explicitly names the column "nsfw"
    private boolean nsfwDetected;

    // Optional fields from the solution's SQL schema
    private String source;
    private String actorId; // Snake case in SQL is actor_id, but Java uses camelCase with JPA mapping it automatically

    // For timestamp:
    // @CreationTimestamp // Automatically sets the timestamp on entity creation (Hibernate specific)
    @Column(nullable = false)
    private LocalDateTime timestamp;

    // JPA requires a no-argument constructor
    public AuditLog() {
        this.timestamp = LocalDateTime.now(); // Default to current time on object creation
    }

    // You can keep a constructor for convenience, but JPA primarily uses the no-arg constructor
    public AuditLog(String original, String sanitized, boolean piiDetected, boolean nsfwDetected, String source, String actorId) {
        // No ID in this constructor, as it will be generated by the database or JPA
        this(); // Call the no-arg constructor to set timestamp
        this.original = original;
        this.sanitized = sanitized;
        this.piiDetected = piiDetected;
        this.nsfwDetected = nsfwDetected;
        this.source = source;
        this.actorId = actorId;
    }

    // --- Getters and Setters (JPA often requires setters for updates, or you can use builder patterns) ---

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; } // Needed by JPA for hydration

    public String getOriginal() { return original; }
    public void setOriginal(String original) { this.original = original; }

    public String getSanitized() { return sanitized; }
    public void setSanitized(String sanitized) { this.sanitized = sanitized; }

    public boolean isPiiDetected() { return piiDetected; }
    public void setPiiDetected(boolean piiDetected) { this.piiDetected = piiDetected; }

    public boolean isNsfwDetected() { return nsfwDetected; }
    public void setNsfwDetected(boolean nsfwDetected) { this.nsfwDetected = nsfwDetected; }

    public LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public String getActorId() { return actorId; }
    public void setActorId(String actorId) { this.actorId = actorId; }

    // Consider overriding equals() and hashCode() if you'll be storing these in collections
    // or comparing them often.
    // Also, a toString() method is useful for logging and debugging.
}